#### Real Time-The aim is to predict either the customer is interested or not in the buying the insurance

#### Reading the files of train and test datasets

In [6]:
import pandas as pd
import numpy as np

In [9]:
clf_train = pd.read_csv("TRAIN.csv")
clf_test = pd.read_csv("TEST.csv")

In [11]:
clf_train.head()

id  Gender  Age  Driving_License  Region_Code  Previously_Insured  \
0  350957    Male   50                1           41                   0   
1  239788  Female   48                1           28                   0   
2  348272  Female   34                1           41                   0   
3   73940  Female   43                1           28                   0   
4  292871    Male   29                1           28                   1   

  Vehicle_Age Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  \
0    1-2 Year            Yes           35915                   124      240   
1    1-2 Year            Yes           26873                   124      274   
2    1-2 Year            Yes            2630                   156      138   
3    1-2 Year            Yes           46877                   124      223   
4    < 1 Year             No           38009                   152      106   

   Response  
0         0  
1         0  
2         1  
3         0  
4         0

In [8]:
clf_train.columns

Index(['id', 'Gender', 'Age', 'Driving_License', 'Region_Code',
       'Previously_Insured', 'Vehicle_Age', 'Vehicle_Damage', 'Annual_Premium',
       'Policy_Sales_Channel', 'Vintage', 'Response'],
      dtype='object')

In [2332]:
clf_train.shape

(304887, 12)

In [2333]:
clf_test.shape

(76222, 11)

#####displaying the unique values of the target variable

In [2334]:
clf_train["Response"].unique()

array([0, 1])

####checking for the NaN values in the data set

In [2335]:
clf_train.isna().any()

id                      False
Gender                  False
Age                     False
Driving_License         False
Region_Code             False
Previously_Insured      False
Vehicle_Age             False
Vehicle_Damage          False
Annual_Premium          False
Policy_Sales_Channel    False
Vintage                 False
Response                False
dtype: bool

In [2336]:
clf_train["Response"].value_counts()

0    267582
1     37305
Name: Response, dtype: int64

In [2337]:
clf_train.head()

id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
0  350957    Male   50  ...                   124      240         0
1  239788  Female   48  ...                   124      274         0
2  348272  Female   34  ...                   156      138         1
3   73940  Female   43  ...                   124      223         0
4  292871    Male   29  ...                   152      106         0

[5 rows x 12 columns]

In [2338]:
clf_test.head()

id  Gender  Age  ...  Annual_Premium  Policy_Sales_Channel  Vintage
0  291378    Male   31  ...            2630                   156      152
1  154746  Female   24  ...           28105                   152      267
2  218512  Female   25  ...           29302                   152      139
3  173930    Male   49  ...           28357                    26       12
4  241471    Male   55  ...           33288                    26       44

[5 rows x 11 columns]

In [2339]:
clf_train["Vehicle_Age"].unique()

array(['1-2 Year', '< 1 Year', '> 2 Years'], dtype=object)

##### Converting the categorical data to numbers , we are doing label encoding, just I have raplaced it with 0 and 1,2 in the below sections

In [2340]:
clf_train["Gender"].replace(["Male","Female"],[1,0],inplace = True)

In [2341]:
clf_train["Gender"]

0         1
1         0
2         0
3         0
4         1
         ..
304882    1
304883    1
304884    0
304885    0
304886    0
Name: Gender, Length: 304887, dtype: int64

In [2342]:
clf_train["Vehicle_Age"].replace(["1-2 Year","< 1 Year","> 2 Years"],[1,0,2],inplace = True)

In [2343]:
clf_train["Vehicle_Age"].unique()

array([1, 0, 2])

In [2344]:
clf_train["Vehicle_Damage"].replace(["Yes","No"],[1,0],inplace = True)

In [2345]:
clf_train["Vehicle_Damage"].unique()

array([1, 0])

In [2346]:
clf_train.head()

id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
0  350957       1   50  ...                   124      240         0
1  239788       0   48  ...                   124      274         0
2  348272       0   34  ...                   156      138         1
3   73940       0   43  ...                   124      223         0
4  292871       1   29  ...                   152      106         0

[5 rows x 12 columns]

#### seperate the features and the target labels

In [2347]:
clf_features = clf_train.drop(["Response","id","Region_Code","Annual_Premium"],axis=1)

In [2348]:
clf_features.head()

Gender  Age  Driving_License  ...  Vehicle_Damage  Policy_Sales_Channel  Vintage
0       1   50                1  ...               1                   124      240
1       0   48                1  ...               1                   124      274
2       0   34                1  ...               1                   156      138
3       0   43                1  ...               1                   124      223
4       1   29                1  ...               0                   152      106

[5 rows x 8 columns]

In [2349]:
clf_target = pd.DataFrame(clf_train["Response"])

In [2350]:
clf_target.head()

Response
0         0
1         0
2         1
3         0
4         0

In [2351]:
clf_train["Region_Code"].unique()

array([41, 28, 16, 46, 18, 39,  6, 35,  1, 38,  8, 24, 33, 30, 10, 25, 22,
        3, 11, 50, 17, 15, 32, 47, 29, 21, 37,  9, 14, 48, 40, 23, 43, 45,
        0, 36, 13,  2, 52, 34, 26, 31,  5, 27, 42,  7, 12,  4, 49, 20, 19,
       44, 51])

In [2352]:
clf_train["Annual_Premium"].unique()

array([ 35915,  26873,   2630, ...,  14914,  48852, 130427])

In [2353]:
clf_train["Age"].unique()

array([50, 48, 34, 43, 29, 62, 47, 57, 23, 63, 42, 60, 22, 25, 24, 33, 66,
       37, 39, 31, 55, 49, 38, 77, 36, 80, 21, 26, 40, 27, 56, 44, 20, 68,
       54, 64, 59, 52, 69, 46, 32, 30, 58, 51, 70, 41, 53, 61, 73, 28, 72,
       45, 35, 67, 75, 79, 71, 78, 65, 83, 76, 74, 84, 85, 81, 82])

In [2354]:
clf_train["Policy_Sales_Channel"].unique()

array([124, 156, 152,  26, 131, 154,  10, 160, 122,  24,  13, 155, 147,
       157, 121,  14,  30, 151,  25, 163,  40, 138,   8,  12,  16, 120,
        15,   4, 109,  61,  29,  23,   1,  60,  22,  31,  92,  87, 125,
        52, 150,   3,  94,  55,  11,  18,   9, 133, 153,   7, 136,  19,
        63,  35, 132,  95, 158, 140,  78,  81,  59, 113, 103, 105,  47,
       116,  73,  53,  97, 127, 108, 145,  91, 111,  54,  93, 130, 146,
       135,  46, 129,  42, 148, 117,  80,  20,  21,  45, 139,  88,  37,
       119,  44, 107,  98,  32, 128,  56, 134,  36,  86, 159,  96, 100,
        49, 114,  90, 126, 106,  64,   6,  65,  39,  17, 101,  79,  62,
       118,  48, 115,  58,  71,  75, 102,  51,  57, 137,  89,   2,  66,
        27, 104,  41,  82,  38,  70,  83, 110,  99,  69,  50,  74,  68,
        67,  34, 112,  33,  76,  28, 143,  84])

#### in the above section the numbers are having a huge difference so le us do the nomarlization or scaling to numbers , so that the numbers are in certain range

In [2355]:
from sklearn.preprocessing import StandardScaler
scale_feat = StandardScaler()
faeture_scaled = scale_feat.fit_transform(clf_features)

In [2356]:
faeture_scaled

array([[ 0.92183747,  0.71952278,  0.04615089, ...,  0.99051034,
         0.22094799,  1.02381674],
       [-1.08478993,  0.59066213,  0.04615089, ...,  0.99051034,
         0.22094799,  1.42996573],
       [-1.08478993, -0.31136241,  0.04615089, ...,  0.99051034,
         0.81122212, -0.19463025],
       ...,
       [-1.08478993,  0.46180148,  0.04615089, ...,  0.99051034,
         0.77432999,  0.00844425],
       [-1.08478993,  2.45914154,  0.04615089, ..., -1.00958057,
         0.18405585, -1.12638382],
       [-1.08478993, -0.89123533,  0.04615089, ..., -1.00958057,
         0.73743785, -0.4096503 ]])

#### Now let us train the model

In [2357]:
from sklearn.model_selection import train_test_split
trainx,testx,trainy,testy = train_test_split(faeture_scaled,clf_target,test_size = 0.25,random_state=40)

In [2358]:
print(trainx.shape,testx.shape)

(228665, 8) (76222, 8)


In [2359]:
from sklearn.linear_model import LogisticRegression
log_model = LogisticRegression()
log_model.fit(trainx,trainy)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

#### before we test the data on the TEST data set let us label the data and normalize the data that model can easily predict the data

In [2360]:
clf_test["Gender"].replace(["Male","Female"],[1,0],inplace = True)

In [2361]:
clf_test["Vehicle_Age"].replace(["1-2 Year","< 1 Year","> 2 Years"],[1,0,2],inplace = True)

In [2362]:
clf_test["Vehicle_Damage"].replace(["Yes","No"],[1,0],inplace = True)

In [2363]:
clf_test1 = clf_test.drop(["id","Region_Code","Annual_Premium"],axis=1)

In [2364]:
clf_test1.head()

Gender  Age  Driving_License  ...  Vehicle_Damage  Policy_Sales_Channel  Vintage
0       1   31                1  ...               1                   156      152
1       0   24                1  ...               0                   152      267
2       0   25                1  ...               0                   152      139
3       1   49                1  ...               1                    26       12
4       1   55                1  ...               1                    26       44

[5 rows x 8 columns]

#### Accuracy of the model without scaling or normalizing the data

In [2365]:
model_predict = log_model.predict(clf_test1)

In [2366]:
model_predict

array([0, 0, 0, ..., 0, 0, 0])

In [2367]:
from sklearn.metrics import accuracy_score,confusion_matrix
confu_matrix =  confusion_matrix(model_predict,testy)


In [2368]:
confu_matrix

array([[66875,  9347],
       [    0,     0]])

In [2369]:
accuracy = accuracy_score(model_predict,testy)

In [2370]:
print(np.round(accuracy*100,2),end="%")

87.74%

#### After normalising or scaling the test data set the accuracy and the confusion matrix

In [2371]:
from sklearn.preprocessing import StandardScaler
scale_test = StandardScaler()
test_scaled = scale_test.fit_transform(clf_test1)

In [2372]:
test_scaled

array([[ 0.92037471, -0.5029147 ,  0.04643543, ...,  0.98942902,
         0.81069509, -0.03071224],
       [-1.08651399, -0.95524934,  0.04643543, ..., -1.01068392,
         0.73685509,  1.34648509],
       [-1.08651399, -0.89063011,  0.04643543, ..., -1.01068392,
         0.73685509, -0.18639541],
       ...,
       [ 0.92037471,  0.78947   ,  0.04643543, ..., -1.01068392,
         0.21997509, -0.25824918],
       [ 0.92037471, -1.14910704,  0.04643543, ..., -1.01068392,
         0.88453509, -0.91690877],
       [-1.08651399,  0.27251612,  0.04643543, ...,  0.98942902,
         0.73685509,  1.46624137]])

In [2373]:
model_predict = log_model.predict(test_scaled)

In [2374]:
pd.DataFrame(model_predict)

0
0      0
1      0
2      0
3      0
4      0
...   ..
76217  0
76218  0
76219  0
76220  0
76221  0

[76222 rows x 1 columns]

In [2375]:
testy

Response
62761          0
99685          0
220460         0
56346          0
270589         0
...          ...
186498         0
164515         0
202568         0
149437         0
104960         0

[76222 rows x 1 columns]

In [2376]:
from sklearn.metrics import accuracy_score,confusion_matrix
confu_matrix =  confusion_matrix(model_predict,testy)


In [2377]:
confu_matrix

array([[66841,  9342],
       [   34,     5]])

In [2378]:
print(testx.shape,testy.shape)

(76222, 8) (76222, 1)


In [2379]:
accuracy =  accuracy_score(model_predict,testy)

In [2380]:
print(np.round(accuracy*100,2),end="%")

87.7%

In [2384]:
output_csv =pd.DataFrame()
output_csv["id"] = clf_test["id"]
output_csv["Response"] = pd.DataFrame(model_predict)

In [2385]:
output_csv["Response"].unique()

array([0, 1])

In [2386]:
output_csv.to_csv("output_csv.csv")